/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IGatewayInterface extends ethers.utils.Interface {
  functions: {
    "crossChainRequestDefaultFee()": FunctionFragment;
    "currentVersion()": FunctionFragment;
    "iSend(uint256,uint256,string,string,bytes,bytes)": FunctionFragment;
    "setDappMetadata(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "crossChainRequestDefaultFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "iSend",
    values: [BigNumberish, BigNumberish, string, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDappMetadata",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "crossChainRequestDefaultFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "iSend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDappMetadata",
    data: BytesLike
  ): Result;

  events: {};
}

export class IGateway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IGatewayInterface;

  functions: {
    crossChainRequestDefaultFee(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fees: BigNumber }>;

    currentVersion(overrides?: CallOverrides): Promise<[BigNumber]>;

    iSend(
      version: BigNumberish,
      routeAmount: BigNumberish,
      routeRecipient: string,
      destChainId: string,
      requestMetadata: BytesLike,
      requestPacket: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDappMetadata(
      feePayerAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  crossChainRequestDefaultFee(overrides?: CallOverrides): Promise<BigNumber>;

  currentVersion(overrides?: CallOverrides): Promise<BigNumber>;

  iSend(
    version: BigNumberish,
    routeAmount: BigNumberish,
    routeRecipient: string,
    destChainId: string,
    requestMetadata: BytesLike,
    requestPacket: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDappMetadata(
    feePayerAddress: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    crossChainRequestDefaultFee(overrides?: CallOverrides): Promise<BigNumber>;

    currentVersion(overrides?: CallOverrides): Promise<BigNumber>;

    iSend(
      version: BigNumberish,
      routeAmount: BigNumberish,
      routeRecipient: string,
      destChainId: string,
      requestMetadata: BytesLike,
      requestPacket: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setDappMetadata(
      feePayerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    crossChainRequestDefaultFee(overrides?: CallOverrides): Promise<BigNumber>;

    currentVersion(overrides?: CallOverrides): Promise<BigNumber>;

    iSend(
      version: BigNumberish,
      routeAmount: BigNumberish,
      routeRecipient: string,
      destChainId: string,
      requestMetadata: BytesLike,
      requestPacket: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDappMetadata(
      feePayerAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    crossChainRequestDefaultFee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    iSend(
      version: BigNumberish,
      routeAmount: BigNumberish,
      routeRecipient: string,
      destChainId: string,
      requestMetadata: BytesLike,
      requestPacket: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDappMetadata(
      feePayerAddress: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
