/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IDapp, IDappInterface } from "../IDapp";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestIdentifier",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "execFlags",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "execData",
        type: "bytes",
      },
    ],
    name: "iAck",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "requestSender",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "packet",
        type: "bytes",
      },
      {
        internalType: "string",
        name: "srcChainId",
        type: "string",
      },
    ],
    name: "iReceive",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDapp__factory {
  static readonly abi = _abi;
  static createInterface(): IDappInterface {
    return new utils.Interface(_abi) as IDappInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IDapp {
    return new Contract(address, _abi, signerOrProvider) as IDapp;
  }
}
