/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IXERC721, IXERC721Interface } from "../IXERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "chainId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "transferCrossChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IXERC721__factory {
  static readonly abi = _abi;
  static createInterface(): IXERC721Interface {
    return new utils.Interface(_abi) as IXERC721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IXERC721 {
    return new Contract(address, _abi, signerOrProvider) as IXERC721;
  }
}
